Add GraalVM for JDK 21 Community 21.0.1
quarkusio/quarkus-images pull request #256
Opened 2023-10-26 13:55 UTC by manofthepeace

Not sure I did it properly. Apologies if I did not.

2023-10-26 14:03 UTC, zakkak requested changes
Hi @manofthepeace, thanks for the PR. Please have a look at my comments.

2023-10-26 14:03 UTC, zakkak commented on quarkus-native-s2i/graalvm.yaml
> +    tags: jdk-21
You need to remove `tags: jdk-21` from 21.0.0

2023-10-26 14:03 UTC, zakkak commented on quarkus-graalvm-builder-image/graalvm.yaml
> +    tags: jdk-21
You need to remove `tags: jdk-21` from 21.0.0

2023-10-26 14:15 UTC, manofthepeace commented
Thank you @zakkak . Done

2023-10-26 14:26 UTC, zakkak approved these changes
LGTM. Thanks @manofthepeace

2023-10-26 17:21 UTC, merged

2023-10-26 17:21 UTC, cescoffier commented
Thanks!

2023-10-27 12:49 UTC, manofthepeace commented
Can this be pushed to quay?

2023-10-27 14:57 UTC, cescoffier commented
I just triggered the publication.